[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 200
viaIR = true

fs_permissions = [{ access = "read", path = "./" }]

[invariant]

run = 1024
depth = 30
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
