name: Verify on scan

on:
  push:

jobs:
  foundry-test:
    strategy:
      fail-fast: true

    name: Verify on scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: pnpm/action-setup@v2.2.4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: verify on bnbTest
        run: pnpm run verify --network bnbTest
        env:
          BNB_SCAN_API_KEY: ${{ secrets.BNB_SCAN_API_KEY }}
          BNB_CHAIN_TEST_URL: ${{ secrets.BNB_CHAIN_TEST_URL }}
    
      - name: verify on polygon mumbai
        run: pnpm run verify --network mumbai
        env:
          POLYGON_SCAN_API_KEY: ${{ secrets.POLYGON_SCAN_API_KEY }}
          POLYGON_MUMBAI_RPC_URL: ${{ secrets.POLYGON_MUMBAI_RPC_URL }}
